### ISSUE TITLE
【DEV】eslintやprettierの設定とhuskyの導入

### ISSUE THREAD

**Issue by KohnoTaiyo** [qin-team-recipe/10-recipe-app#10]
コード品質を保つためにルールの導入を行う。

**Comment by yoko-at-home** [comment]
Qinサロンで紹介されていた便利ESLintプラグイン導入されますか？
[eslint-plugin-sort-keys-custom-order](https://qin.salon/archives/bBiia4iVNUcGwcIKSZRW)（オブジェクト等の自動ソート）
[eslint-plugin-simple-import-sort](https://qin.salon/archives/uexYr9udmk5ePhHt6Eju)（import・export文の自動ソート）
[eslint-plugin-unused-imports](https://qin.salon/archives/0soYzBqyJbQ5oZ12E6fp)（使っていないものを自動削除）

**Comment by KohnoTaiyo** [comment]
@yoko-at-home 
めちゃくちゃいいすね。入れます。
