### ISSUE TITLE
【FE】buildエラーの解消のため、お気に入り/my Recipeページの一部修正

### ISSUE THREAD

**Issue by KohnoTaiyo** [qin-team-recipe/10-recipe-app#104]
## 概要
パス的には src/app/fav/my/page.tsx のLink href部分の修正。
エラー内容を見て解消する。

![スクリーンショット 2023-08-11 15 19 51](https://github.com/qin-team-recipe/10-recipe-app/assets/59274850/705be12a-efe9-464d-9c24-f925e3a65493)

## 目的
buildエラーがあると本来はそもそもデプロイできないのでbuildエラーを解消する。

## 達成
yarn buildを行なってエラーが出ないようになったらOKです。

**Comment by yoko-at-home** [comment]
@KohnoTaiyo 今このエラーって出ないですよね？
<img width="722" alt="スクリーンショット 2023-08-16 13 36 23" src="https://github.com/qin-team-recipe/10-recipe-app/assets/61738591/72df1a37-8f87-403e-859e-865f701fbc79">

**Comment by yoko-at-home** [comment]
@KohnoTaiyo 再度確認しましたが、以前は「<Link href="recipe/new">マイレシピを追加する</Link>」これでエラーが出ていましたが、どこかのブランチでビルドエラーになり「<Link href="/recipe/new">マイレシピを追加する</Link>」と「/」を入れて対応しました。現在最新のdevelopではビルドエラーになりません。
