### ISSUE TITLE
【FE】セクションタイトルコンポーネントの作成

### ISSUE THREAD

**Issue by KohnoTaiyo** [qin-team-recipe/10-recipe-app#108]
## 概要
セクションタイトルが良く出てくるのでコンポーネント化
要件として
・セクションタイトルが設定できる
・右側にもっと見るを設定できる（pathがpropにあれば表示的な）

画像赤枠のコンポーネント作成

<img width="579" alt="スクリーンショット 2023-08-11 16 58 58" src="https://github.com/qin-team-recipe/10-recipe-app/assets/59274850/a18e6bf1-dfa1-4574-bed2-82b049b75aff">

## 目的
コードの統一

## 達成
コンポーネントの作成

**Comment by yoko-at-home** [comment]
実装済みのためクロースします。
