### ISSUE TITLE
【FE】headerのバランスが崩れているので修正する

### ISSUE THREAD

**Issue by yoko-at-home** [qin-team-recipe/10-recipe-app#136]
## 概要
現状：
<img width="553" alt="スクリーンショット 2023-08-22 23 39 44" src="https://github.com/qin-team-recipe/10-recipe-app/assets/61738591/bb274dca-8f65-48a3-9543-e870c59292c8">
Figma：
<img width="547" alt="スクリーンショット 2023-08-22 23 42 22" src="https://github.com/qin-team-recipe/10-recipe-app/assets/61738591/964ddd13-77e1-4e02-b5b9-236d871a2cc7">

**Comment by artaco** [comment]
@yoko-at-home こちら本日（2023/09/04）時点でのdevelop最新状態では崩れが解消されておりました。ただ、買い物リストページではHeaderコンポーネントが未適用でしたので適用の上、セッション状態による表示の切り替え対応をおこないました。
