### ISSUE TITLE
【FE】app/search/page.tsxページ：chef情報をmock→api取得に切り替える

### ISSUE THREAD

**Issue by yoko-at-home** [qin-team-recipe/10-recipe-app#99]
## 概要
Chefのデータをspabaseに注入したので、現在mockから取得している情報をapi取得に切り替える

## その他
対象ファイル：
src/app/search/page.tsx

参考情報：
sampleページのデータ取得方法を参照

**Comment by KohnoTaiyo** [comment]
実装済み
